### ISSUE TITLE
volumes data folder not working

### ISSUE THREAD

**Issue by nathan-zhu** [docker-library/elasticsearch#108]
Hi, I use official file of es 2.3

but I wannna use local data folder instead of /usr/share/elasticsearch/data folder in container, 

this is my docker-compose file 

```
elasticsearch_master:
    image: elasticsearch:latest
    command: "elasticsearch -Des.cluster.name=workagram -Des.node.master=true -Des.node.data=true"
    volumes:
      - "/opt/data/elasticsearch:/usr/share/elasticsearch/data"
    environment:
       - ES_HEAP_SIZE=512m
    ports:
      - "9200:9200"
      - "9300:9300"
```

and /opt/data/elasticsearch folder i give chmod 777 for it, after running docker-compose up -d, 

docker ps show it running 

```
ONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                            NAMES
6f565f00f935        elasticsearch:latest   "/docker-entrypoint.s"   5 minutes ago       Up 5 minutes        0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   est_elasticsearch_master_1
```

and i can create new index there with
`curl -XPUT 192.168.99.100:9200/abctest`

but i check data folder there is nothing to show, what's wrong with my settings?  
please help thanks.
