### ISSUE TITLE
  Error: Could not find or load main class "-Dmapper.allow_dots_in_name=true"

### ISSUE THREAD

**Issue by oguennec** [docker-library/elasticsearch#137]
**Dockerfile version 2.4 with ELASTICSEARCH_VERSION 2.4.1**

I want to enable support for dots in field names as described in  [https://www.elastic.co/guide/en/elasticsearch/reference/2.4/dots-in-names.html]()

But adding the following environment variable in docker-compose.yml
```
es:
  build: es
  environment:
   - ES_JAVA_OPTS="-Dmapper.allow_dots_in_name=true"
  volumes:
   - $PWD/es/data:/data
  ports:
   - "9200:9200"
   - "9300:9300"
```

results in
`es_1 | Error: Could not find or load main class "-Dmapper.allow_dots_in_name=true"`

**Comment by oguennec** [comment]
I just need to remove the double quotes
```
es:
  build: es
  environment:
   - ES_JAVA_OPTS=-Dmapper.allow_dots_in_name=true
  volumes:
   - $PWD/es/data:/data
  ports:
   - "9200:9200"
   - "9300:9300"
```
