### ISSUE TITLE
How can I change the log level for ES using docker-compose?

### ISSUE THREAD

**Issue by stabenfeldt** [docker-library/elasticsearch#40]
Hi,

I'm running **elasticsearch:1.4.2** on Digital Ocean. ES dies without any errors what so ever. 
Is there a way I can change the log level to DEBUG from `docker-compose.yml`?

Cheers,
Martin

**Comment by yosifkit** [comment]
The default log level is debug: [`logging.yml`](https://github.com/docker-library/elasticsearch/blob/50a531d6b86d418b8107036b940a3a2b9d91635b/1.6/config/logging.yml#L6).  But you can make your own logging config yaml and mount it into `/usr/share/elasticsearch/config/` with `volumes` in your `docker-compose.yml`, just make sure the file permissions are such that the `elasticsearch` user in the container can access it.

**Comment by raylu** [comment]
another option is to change the Dockerfile to
```
CMD ["elasticsearch", "-Des.logger.level=DEBUG"]
```

**Comment by hjhsalo** [comment]
One way to change log level through `docker-compose.yml` if to override the Dockerfile CMD:
```
services:
  elasticsearch:
    image: elasticsearch
    command: ["elasticsearch", "-Elogger.level=DEBUG"]
```
(For me `"-Des.logger.level=DEBUG"` didn't work)

**Comment by Startouf** [comment]
When I add `command: ["elasticsearch", "-Elogger.level=DEBUG"]` it seems to override environment config for develomment mode, and ES won't start with the message 

```
elasticsearch | ERROR: [1] bootstrap checks failed
elasticsearch | [1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
```

COnfig

```
elasticsearch:
  image: xxx
  container_name: elasticsearch
  volumes:
    - .:/app
  command: ["elasticsearch", "-Elogger.level=WARN"]
  environment:
    - cluster.name=elasticsearch
    - xpack.security.enabled=false
    - network.host=0.0.0.0
    - http.port=9200
    - discovery.type=single-node
    # - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
  ports:
    - 9200:9200
    - 9300:9300
```
