### ISSUE TITLE
[Coral] high disk watermark [90%] exceeded

### ISSUE THREAD

**Issue by rosskevin** [docker-library/elasticsearch#55]
We spin up a new container for a CI build and there is currently a very low volume of data being added to the elasticsearch container.  Instantly, we see many of these:

```
[WARN ][cluster.routing.allocation.decider] [Coral] high disk watermark [90%] exceeded on [pwWXZlUxQDmHoLRVijqLWA][Coral] free: 975.6mb[5.2%], shards will be relocated away from this node
```

We are using:

```yaml
elasticsearch:
  image: library/elasticsearch:1.7
  ports:
    - "9200:9200"
```

I'm a bit new to docker/compose, is there a way to allocate a bit more free space to the container to avoid this?
